; To run the application locally:
;  dune build
;  dune exec project_name
;
; The initial 'dune build' is needed to make sure that static files are updated.

(subdir
 local/var/www/project_name
 (rule
  (mode promote)
  (action
   (copy %{workspace_root}/app/client/project_name.bc.js project_name.js)))
 (rule
  (mode promote)
  ; Depend on assets dir as it's not build by default
  (deps project_name.bc.wasm.assets)
  (action
   (copy
    %{workspace_root}/app/client/project_name.bc.wasm.js
    project_name.wasm.js)))
 (rule
  (mode promote)
  ; Name is hardcoded into compiled wasm files
  (targets
   (dir project_name.bc.wasm.assets))
  (deps %{workspace_root}/app/client/project_name.bc.wasm.assets)
  (action
   (run cp -r %{deps} .)))
 (subdir
  css
  (rule
   (mode promote)
   (action
    (copy %{workspace_root}/static/css/project_name.css project_name.css)))))

; Install the www directory

(install
 (section share)
 (package project_name)
 (files
  (app/client/project_name.bc.js as www/project_name.js)
  (app/client/project_name.bc.wasm.js as www/project_name.wasm.js)
  ; It seems that we can't change the wasm assets directory name
  (glob_files_rec
   (app/client/project_name.bc.wasm.assets/**
    with_prefix
    www/project_name.bc.wasm.assets))
  (glob_files_rec
   (static/** with_prefix www))))
